"""S1 simulation core: truth + estimators for supIPM / EIPM.  numpy / scipy only.

Model (spec S1 sec.1)
    S ~ N(0,1),   Z | S=s ~ N(mu(s), sigma_c^2),   sigma_c^2 = 1 - Var(mu(S))
so Var(Z) = 1 exactly.  Two choices of mu:
    linear : mu(s) = lam * s                          (closed-form check)
    bump   : mu(s) = kappa*exp(-(s-s0)^2/(2*tau^2))   (main experiment)

Discriminator class = 1-Lipschitz  =>  IPM(s) = W1(P_{Z|S=s}, P_Z), and in 1-D
    W1(s) = int |F_s(u) - F(u)| du .

NOTE this file is generated by s1.ipynb (a %%writefile cell); edit the notebook,
not this file.
"""
import os
import warnings

import numpy as np
from numpy.polynomial.hermite_e import hermegauss
from scipy.special import ndtr          # standard normal CDF, ~5x faster than norm.cdf
from scipy.stats import norm

# ----------------------------------------------------------------- constants
ALPHA = 0.05
Z_TRIM = float(norm.ppf(1 - ALPHA / 2))            # 1.959964...  trimming |s| <= z
U_GRID = np.linspace(-8.0, 8.0, 4001)              # spec sec.2: u integration grid
S_GRID = np.linspace(-Z_TRIM, Z_TRIM, 5001)        # spec sec.2: s grid for the sup
GH_NODES = 101                                     # spec sec.2: Gauss-Hermite nodes
N_EIPM = 500                                       # spec sec.3: MC size for EIPM_hat
JS_DEFAULT = (2, 3, 5, 10, 20)                     # spec sec.4 C3
MIN_BIN_COUNT = 10                                 # spec sec.3: drop bins with < 10 obs


# --------------------------------------------------------------------- model
def mu_of(kind, **p):
    """Return the mean function mu(.) for the given setting."""
    if kind == "linear":
        lam = float(p.get("lam", 0.5))
        return lambda s: lam * np.asarray(s, dtype=float)
    if kind == "bump":
        kappa = float(p.get("kappa", 1.2))
        s0 = float(p.get("s0", 0.7))
        tau = float(p.get("tau", 0.2))
        return lambda s: kappa * np.exp(-(np.asarray(s, dtype=float) - s0) ** 2 / (2 * tau ** 2))
    raise ValueError(f"unknown mu kind: {kind}")


def var_mu_exact(kind, **p):
    """Var(mu(S)) in closed form, S ~ N(0,1).

    bump: E[exp(-(S-s0)^2/(2 t^2))] = t/sqrt(1+t^2) * exp(-s0^2/(2(1+t^2))),
    applied with t = tau (first moment) and t = tau/sqrt(2) (second moment).
    Using the exact value (rather than quadrature) makes Var(Z) = 1 exactly.
    """
    if kind == "linear":
        return float(p.get("lam", 0.5)) ** 2
    if kind == "bump":
        kappa = float(p.get("kappa", 1.2))
        s0 = float(p.get("s0", 0.7))
        tau = float(p.get("tau", 0.2))
        g = lambda t: t / np.sqrt(1 + t ** 2) * np.exp(-s0 ** 2 / (2 * (1 + t ** 2)))
        m1 = kappa * g(tau)
        m2 = kappa ** 2 * g(tau / np.sqrt(2))
        return float(m2 - m1 ** 2)
    raise ValueError(f"unknown mu kind: {kind}")


def make_model(kind="bump", **p):
    var_mu = var_mu_exact(kind, **p)
    if var_mu >= 1.0:
        raise ValueError(f"Var(mu(S)) = {var_mu:.4f} >= 1 -> sigma_c^2 <= 0")
    return {"kind": kind, "params": dict(p), "mu": mu_of(kind, **p),
            "var_mu": var_mu, "sigma_c": float(np.sqrt(1.0 - var_mu))}


def model_tag(model):
    ps = "_".join(f"{k}{v:g}" for k, v in sorted(model["params"].items()))
    return f"{model['kind']}" + (f"_{ps}" if ps else "")


# ---------------------------------------------------------------- quadrature
def gh_quad(m=GH_NODES):
    """Gauss-Hermite (probabilists') nodes/weights for E_S[f(S)], S ~ N(0,1).

    numpy's hermegauss emits harmless divide/overflow warnings while building the
    weights; the returned weights are finite and sum to sqrt(2*pi) for m <= ~300.
    """
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        x, w = hermegauss(m)
    if not np.isfinite(w).all():
        raise RuntimeError(f"hermegauss({m}) produced non-finite weights")
    return x, w / np.sqrt(2 * np.pi)                 # weights now sum to 1


def trap_quad(m=20001, lo=-10.0, hi=10.0):
    """Dense trapezoid reference rule for E_S[f(S)] (accuracy cross-check)."""
    x = np.linspace(lo, hi, m)
    w = norm.pdf(x) * (x[1] - x[0])
    w[0] *= 0.5
    w[-1] *= 0.5
    return x, w / w.sum()


# --------------------------------------------------------------------- truth
def marginal_cdf(model, u=U_GRID, quad=None, block=2048):
    """F(u) = E_S[ Phi((u - mu(S))/sigma_c) ]."""
    x, w = gh_quad() if quad is None else quad
    m = model["mu"](x)
    sc = model["sigma_c"]
    F = np.zeros(u.size)
    for i in range(0, m.size, block):
        j = min(i + block, m.size)
        F += w[i:j] @ ndtr((u[None, :] - m[i:j, None]) / sc)
    return F


def w1_true_at_mu(m_vals, sigma_c, F, u=U_GRID, block=512):
    """W1(s) = int |Phi((u-mu(s))/sigma_c) - F(u)| du, vectorised over mu(s)."""
    m_vals = np.atleast_1d(np.asarray(m_vals, dtype=float))
    du = u[1] - u[0]
    out = np.empty(m_vals.size)
    for i in range(0, m_vals.size, block):
        j = min(i + block, m_vals.size)
        D = np.abs(ndtr((u[None, :] - m_vals[i:j, None]) / sigma_c) - F[None, :])
        out[i:j] = np.trapz(D, dx=du, axis=1)
    return out


def truth(model, u=U_GRID, s_grid=S_GRID, quad=None):
    """supIPM_true (max over the trimmed s grid) and EIPM_true (phi-weighted mean)."""
    F = marginal_cdf(model, u, quad)
    w1 = w1_true_at_mu(model["mu"](s_grid), model["sigma_c"], F, u)
    phi = norm.pdf(s_grid)
    return {"s_grid": s_grid, "w1": w1, "F": F,
            "supipm": float(w1.max()), "s_argmax": float(s_grid[w1.argmax()]),
            "eipm": float(np.trapz(w1 * phi, s_grid) / np.trapz(phi, s_grid))}


def w1_linear_closed_form(s, lam, sigma_c):
    """Spec sec.2: with b = sigma_c - 1 and a = lam*s,
        W1(s) = |b| sqrt(2/pi) exp(-a^2/(2b^2)) + a (2 Phi(a/|b|) - 1)
    (this is E|N(a, b^2)|; the two normal CDFs cross exactly once)."""
    b = abs(sigma_c - 1.0)
    a = lam * np.asarray(s, dtype=float)
    return b * np.sqrt(2 / np.pi) * np.exp(-a ** 2 / (2 * b ** 2)) + a * (2 * ndtr(a / b) - 1)


def truth_cached(model, cache_dir, gh_nodes=GH_NODES, verbose=False):
    """Truth is deterministic -> compute once per model and reuse (also by workers)."""
    os.makedirs(cache_dir, exist_ok=True)
    path = os.path.join(cache_dir, f"truth_{model_tag(model)}_gh{gh_nodes}.npz")
    if os.path.exists(path):
        with np.load(path) as d:
            out = {k: d[k] for k in d.files}
        for k in ("supipm", "eipm", "s_argmax"):
            out[k] = float(out[k])
        return out
    t = truth(model, quad=gh_quad(gh_nodes))
    np.savez_compressed(path, **t)
    if verbose:
        print(f"[truth] computed and cached -> {path}")
    return t


# ----------------------------------------------------------------- estimator
def simulate(n, model, rng):
    s = rng.standard_normal(n)
    z = model["mu"](s) + model["sigma_c"] * rng.standard_normal(n)
    return s, z


def prep(s, z):
    """Sort by z once; the step-function integral is then an exact finite sum."""
    order = np.argsort(z)
    zs = z[order]
    n = z.size
    return {"s_sorted": s[order], "gaps": np.diff(zs), "F_emp": np.arange(1, n + 1) / n, "n": n}


def w1_hat(points, P, h, max_elems=20_000_000):
    """W1_hat(s) for every s in `points` (spec sec.3).

        w_i(s)      = K_h(s-s_i)/sum_j K_h(s-s_j)      (Gaussian kernel)
        F_s_hat(u)  = sum_i w_i(s) 1(z_i <= u),   F_hat(u) = (1/n) sum_i 1(z_i <= u)
        W1_hat(s)   = sum_k |F_s_hat - F_hat|(z_(k)) * (z_(k+1) - z_(k))

    The exponent is shifted by its row max before exp() -- an exact rescaling of
    numerator and denominator, which keeps the weights well defined when a grid
    point is far from every s_i.
    """
    pts = np.atleast_1d(np.asarray(points, dtype=float))
    ss, gaps, F_emp, n = P["s_sorted"], P["gaps"], P["F_emp"], P["n"]
    block = max(1, int(max_elems // n))
    out = np.empty(pts.size)
    for i in range(0, pts.size, block):
        j = min(i + block, pts.size)
        e = -0.5 * ((pts[i:j, None] - ss[None, :]) / h) ** 2
        e -= e.max(axis=1, keepdims=True)
        Kw = np.exp(e)
        W = Kw / Kw.sum(axis=1, keepdims=True)
        F_cond = np.cumsum(W, axis=1)
        out[i:j] = np.abs(F_cond[:, :-1] - F_emp[:-1]) @ gaps
    return out


def bandwidth(n, c):
    return c * n ** (-1 / 5)


def grid_of(ratio, h):
    """Equispaced grid on [-z, z] with spacing delta_G such that delta_G/h = ratio."""
    G = int(np.ceil(2 * Z_TRIM / (ratio * h))) + 1
    return np.linspace(-Z_TRIM, Z_TRIM, G), G


def binning_sup(P, Js=JS_DEFAULT, min_count=MIN_BIN_COUNT, trim=False):
    """Baseline (spec sec.3): split s into J equal-frequency bins, W1 between each
    bin's empirical z-distribution and the overall empirical distribution, take max.
    Bins with fewer than `min_count` observations are dropped.

    trim=False is the spec's version (quantiles over the whole sample).  trim=True
    is a diagnostic: quantiles and bin membership restricted to |s| <= Z_TRIM, i.e.
    the same region the kernel grid covers.  The reference F_hat always uses all n.
    """
    ss, gaps, F_emp, n = P["s_sorted"], P["gaps"], P["F_emp"], P["n"]
    use = np.abs(ss) <= Z_TRIM if trim else np.ones(n, dtype=bool)
    s_use = ss[use]
    out = {}
    for J in Js:
        q = np.quantile(s_use, np.linspace(0, 1, J + 1))
        b = np.searchsorted(q[1:-1], ss, side="right")          # bin index in 0..J-1
        M = np.zeros((J, n))
        M[b, np.arange(n)] = use
        cnt = M.sum(axis=1)
        keep = cnt >= min_count
        if not keep.any():
            out[J] = float("nan")
            continue
        F_bin = np.cumsum(M[keep] / cnt[keep, None], axis=1)
        out[J] = float((np.abs(F_bin[:, :-1] - F_emp[:-1]) @ gaps).max())
    return out


def run_rep(n, c, ratio, seed, model, js=JS_DEFAULT, n_eipm=N_EIPM, with_binning=True):
    """One replication: draw data, return every estimate computed on it.

    The rng stream is (s, z, EIPM subsample) in that order, so two configurations
    sharing (n, seed) see *identical* data and identical EIPM evaluation points
    -> the comparisons in C2/C3 are exactly paired.
    """
    rng = np.random.default_rng(seed)
    s, z = simulate(n, model, rng)
    inside = np.flatnonzero(np.abs(s) <= Z_TRIM)
    sel = rng.choice(inside, size=min(n_eipm, inside.size), replace=False)

    h = bandwidth(n, c)
    grid, G = grid_of(ratio, h)
    P = prep(s, z)
    rep = {"sup": float(w1_hat(grid, P, h).max()),
           "eipm": float(w1_hat(s[sel], P, h).mean()),
           "G": G, "h": h, "n_eipm": int(sel.size)}
    if with_binning:
        rep["bins"] = binning_sup(P, js, trim=False)
        rep["bins_trim"] = binning_sup(P, js, trim=True)
    return rep


def seed_of(r, seed0=1000, step=7919):
    """Spec sec.4: seed = 1000 + 7919*r, identical across configurations."""
    return seed0 + step * r


# ------------------------------------------------- deterministic h -> limit
# What the estimator converges to as n -> inf with h HELD FIXED.  This is the
# reference that separates "smoothing bias, which theory predicts" from
# "estimation error".  Note it is a function of h alone -- so the convergence
# rate is governed by h/tau, not by the bandwidth constant c.
def limit_context(model, u=None, m=8001, lo=-8.0, hi=8.0):
    """Precompute the pieces shared by every bandwidth (the expensive part)."""
    u = np.linspace(-8.0, 8.0, 2001) if u is None else u   # 2001 pts is converged
    t = np.linspace(lo, hi, m)
    ft = norm.pdf(t)
    PHI = ndtr((u[None, :] - model["mu"](t)[:, None]) / model["sigma_c"])
    return {"u": u, "t": t, "ft": ft, "PHI": PHI, "F": (ft / ft.sum()) @ PHI}


def limit_w1(ctx, h, s_eval, block=64):
    """W1_h(s) = int |F_s^h(u) - F(u)| du,
    F_s^h(u) = int phi_h(s-t) phi(t) Phi((u-mu(t))/sigma_c) dt / int phi_h(s-t) phi(t) dt."""
    s_eval = np.atleast_1d(np.asarray(s_eval, dtype=float))
    u, t, ft, PHI, F = ctx["u"], ctx["t"], ctx["ft"], ctx["PHI"], ctx["F"]
    out = np.empty(s_eval.size)
    for i in range(0, s_eval.size, block):
        j = min(i + block, s_eval.size)
        W = np.exp(-0.5 * ((s_eval[i:j, None] - t[None, :]) / h) ** 2) * ft[None, :]
        W /= W.sum(axis=1, keepdims=True)
        out[i:j] = np.trapz(np.abs(W @ PHI - F[None, :]), dx=u[1] - u[0], axis=1)
    return out


def limit_sup(ctx, h, coarse=201, refine=41):
    """max_s W1_h(s) over the trimmed range: coarse scan, then refine near the argmax."""
    g = np.linspace(-Z_TRIM, Z_TRIM, coarse)
    v = limit_w1(ctx, h, g)
    k = int(v.argmax())
    d = g[1] - g[0]
    g2 = np.linspace(max(g[k] - d, -Z_TRIM), min(g[k] + d, Z_TRIM), refine)
    return float(max(v[k], limit_w1(ctx, h, g2).max()))
