"""S1 runner: build the configuration list, dispatch one Slurm job step per
configuration, collect the .npz results.

Two dispatch modes, chosen automatically (project rule: compute always runs
inside a Slurm allocation, never straight on the shell):

  * outside an allocation  -> each configuration is launched as its own
        srun --partition=idea --cpus-per-task=K --time=... python s1_worker.py ...
  * already inside one (e.g. the notebook itself was started under
    `srun --pty bash` or `srun ... jupyter`) -> workers run as plain
    subprocesses of this process, so they stay inside the granted allocation
    and no nested job step is created.

Everything is cache-aware: a configuration whose .npz already holds the
requested number of replications is skipped, so re-running is free.

NOTE this file is generated by s1.ipynb (a %%writefile cell); edit the notebook.
"""
import json
import os
import shutil
import subprocess
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import s1_core as C

PY = os.environ.get("S1_PYTHON", "/usr/local/miniconda3/envs/nine/bin/python")
RESULTS = os.path.join(HERE, "results")
LOGS = os.path.join(HERE, "logs")
FIGURES = os.path.join(HERE, "figures")
PARTITION = os.environ.get("S1_PARTITION", "idea")
TIME_LIMIT = os.environ.get("S1_TIME", "01:00:00")

IN_ALLOCATION = bool(os.environ.get("SLURM_JOB_ID"))
HAVE_SRUN = shutil.which("srun") is not None

# ------------------------------------------------------------------- design
BUMP = {"kind": "bump", "kappa": 1.2, "s0": 0.7, "tau": 0.2}
REPS = 100
N_LIST = [500, 1000, 2000, 5000, 10000, 20000]      # C1
RATIO_LIST = [0.25, 0.5, 1.0, 2.0, 4.0, 8.0]        # C2
JS = list(C.JS_DEFAULT)                             # C3
C_BASE, RATIO_BASE, N_BASE = 1.0, 0.5, 10000        # spec's fixed values
C_EXTRA = [0.25, 0.5]                               # C1b (supplementary, not in the spec)


def job(n, c, ratio, model=None, reps=REPS):
    model = model or BUMP
    p = {k: v for k, v in model.items() if k != "kind"}
    mt = C.model_tag({"kind": model["kind"], "params": p})
    tag = f"{mt}__n{n}_c{c:g}_r{ratio:g}"
    return {"tag": tag, "n": n, "c": c, "ratio": ratio, "reps": reps,
            "model": model, "out": os.path.join(RESULTS, tag + ".npz")}


def _dedup(js):
    seen, out = set(), []
    for j in js:
        if j["tag"] not in seen:
            seen.add(j["tag"])
            out.append(j)
    return out


def jobs_c1():
    return [job(n, C_BASE, RATIO_BASE) for n in N_LIST]


def jobs_c2():
    return [job(N_BASE, C_BASE, r) for r in RATIO_LIST]


def jobs_c3():
    return [job(N_BASE, C_BASE, RATIO_BASE)]        # binning shares the C1/C2 draws


def jobs_c1b():
    return [job(n, c, RATIO_BASE) for c in C_EXTRA for n in N_LIST]


def all_jobs(include_supplementary=True):
    js = jobs_c1() + jobs_c2() + jobs_c3()
    if include_supplementary:
        js += jobs_c1b()
    return _dedup(js)


# ------------------------------------------------------------------ caching
def is_done(j):
    if not os.path.exists(j["out"]):
        return False
    try:
        with np.load(j["out"], allow_pickle=False) as d:
            return int(d["reps"]) >= j["reps"] and d["sup_hat"].size >= j["reps"]
    except Exception:
        return False


def load(j):
    with np.load(j["out"], allow_pickle=False) as d:
        out = {k: d[k] for k in d.files if k != "meta"}
        out["meta"] = json.loads(str(d["meta"])) if "meta" in d.files else {}
    return out


def load_many(js):
    return {j["tag"]: load(j) for j in js}


# ---------------------------------------------------------------- dispatch
def _cmd(j, cpus):
    m = j["model"]
    args = [PY, "-u", os.path.join(HERE, "s1_worker.py"),
            "--out", j["out"], "--n", str(j["n"]), "--c", str(j["c"]),
            "--ratio", str(j["ratio"]), "--reps", str(j["reps"]),
            "--kind", m["kind"], "--js", ",".join(str(x) for x in JS)]
    for k in ("kappa", "s0", "tau", "lam"):
        if k in m:
            args += [f"--{k}", str(m[k])]
    if IN_ALLOCATION or not HAVE_SRUN:
        return args
    name = f"s1-n{j['n']}c{j['c']:g}r{j['ratio']:g}"          # short + unique in squeue
    return ["srun", f"--partition={PARTITION}", f"--cpus-per-task={cpus}",
            f"--time={TIME_LIMIT}", f"--job-name={name}"] + args


def launch(jobs, max_concurrent=None, cpus=2, force=False, dry=False, poll=3.0):
    """Run every not-yet-finished configuration, at most `max_concurrent` at a time."""
    os.makedirs(RESULTS, exist_ok=True)
    os.makedirs(LOGS, exist_ok=True)
    todo = list(jobs) if force else [j for j in jobs if not is_done(j)]
    if max_concurrent is None:
        budget = int(os.environ.get("SLURM_CPUS_PER_TASK", 0)) or (os.cpu_count() or 4)
        max_concurrent = max(1, min(8, budget // cpus)) if IN_ALLOCATION else 8
    mode = ("in-allocation subprocesses" if IN_ALLOCATION else
            "srun job steps" if HAVE_SRUN else "plain subprocesses (no Slurm found!)")
    print(f"[runner] {len(todo)}/{len(jobs)} to run ({len(jobs) - len(todo)} cached) | "
          f"mode={mode} | max_concurrent={max_concurrent} cpus/job={cpus}", flush=True)
    if dry:
        for j in todo:
            print("  would run:", " ".join(_cmd(j, cpus)))
        return []
    if not todo:
        return []

    env = dict(os.environ, OMP_NUM_THREADS=str(cpus), MKL_NUM_THREADS=str(cpus),
               OPENBLAS_NUM_THREADS=str(cpus))
    queue, running, failed = list(todo), [], []
    t0 = time.time()
    while queue or running:
        for pr, j, fh in running[:]:
            if pr.poll() is None:
                continue
            fh.close()
            running.remove((pr, j, fh))
            ok = is_done(j)
            if not ok:
                failed.append(j["tag"])
            print(f"[runner] {'done ' if ok else 'FAILED'} {j['tag']} (exit {pr.returncode}) | "
                  f"left={len(queue)} running={len(running)} elapsed={time.time() - t0:.0f}s", flush=True)
        while queue and len(running) < max_concurrent:
            j = queue.pop(0)
            fh = open(os.path.join(LOGS, j["tag"] + ".log"), "w")
            pr = subprocess.Popen(_cmd(j, cpus), cwd=HERE, env=env,
                                  stdout=fh, stderr=subprocess.STDOUT)
            print(f"[runner] start {j['tag']}", flush=True)
            running.append((pr, j, fh))
        if queue or running:
            time.sleep(poll)
    print(f"[runner] finished in {time.time() - t0:.0f}s, failures: {len(failed)}", flush=True)
    if failed:
        print("[runner] check logs:", ", ".join(os.path.join(LOGS, t + '.log') for t in failed))
    return failed


def status(jobs):
    rows = [{"tag": j["tag"], "n": j["n"], "c": j["c"], "ratio": j["ratio"],
             "done": is_done(j)} for j in jobs]
    n_done = sum(r["done"] for r in rows)
    print(f"[runner] {n_done}/{len(rows)} configurations complete")
    return rows


if __name__ == "__main__":
    which = sys.argv[1] if len(sys.argv) > 1 else "all"
    sel = {"c1": jobs_c1, "c2": jobs_c2, "c3": jobs_c3, "c1b": jobs_c1b,
           "all": all_jobs, "spec": lambda: _dedup(jobs_c1() + jobs_c2() + jobs_c3())}[which]()
    launch(sel, dry="--dry" in sys.argv, force="--force" in sys.argv)
