"""S1 worker: run all replications of ONE configuration and write one .npz.

Launched by s1_runner.py (one Slurm job step per configuration).  Every estimator
that can share a data draw is computed here, so C1/C2/C3 read from the same file
whenever they share (n, c, ratio) -- the comparisons stay exactly paired.

    python s1_worker.py --out results/K_n10000_c1_r0.5.npz --n 10000 --c 1.0 \
        --ratio 0.5 --reps 100 --kind bump --kappa 1.2 --s0 0.7 --tau 0.2

NOTE this file is generated by s1.ipynb (a %%writefile cell); edit the notebook.
"""
import argparse
import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import s1_core as C


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--n", type=int, required=True)
    ap.add_argument("--c", type=float, required=True)
    ap.add_argument("--ratio", type=float, required=True)
    ap.add_argument("--reps", type=int, default=100)
    ap.add_argument("--kind", default="bump")
    ap.add_argument("--kappa", type=float, default=1.2)
    ap.add_argument("--s0", type=float, default=0.7)
    ap.add_argument("--tau", type=float, default=0.2)
    ap.add_argument("--lam", type=float, default=0.5)
    ap.add_argument("--js", default=",".join(str(j) for j in C.JS_DEFAULT))
    ap.add_argument("--n-eipm", type=int, default=C.N_EIPM)
    ap.add_argument("--gh-nodes", type=int, default=C.GH_NODES)
    ap.add_argument("--seed0", type=int, default=1000)
    ap.add_argument("--seed-step", type=int, default=7919)
    ap.add_argument("--no-binning", action="store_true")
    a = ap.parse_args()

    params = {"lam": a.lam} if a.kind == "linear" else {"kappa": a.kappa, "s0": a.s0, "tau": a.tau}
    model = C.make_model(a.kind, **params)
    js = tuple(int(j) for j in a.js.split(",") if j)

    cache = os.path.dirname(os.path.abspath(a.out))
    os.makedirs(cache, exist_ok=True)
    t = C.truth_cached(model, cache, a.gh_nodes)
    sup_true, eipm_true = t["supipm"], t["eipm"]

    print(f"[worker] n={a.n} c={a.c} ratio={a.ratio} reps={a.reps} "
          f"sigma_c={model['sigma_c']:.6f} sup_true={sup_true:.6f} eipm_true={eipm_true:.6f} "
          f"host={os.uname().nodename} job={os.environ.get('SLURM_JOB_ID', '-')}", flush=True)

    sup = np.empty(a.reps)
    eipm = np.empty(a.reps)
    nbin = len(js)
    bins = np.full((nbin, a.reps), np.nan)
    bins_trim = np.full((nbin, a.reps), np.nan)
    G = h = None
    t0 = time.time()
    for r in range(a.reps):
        rep = C.run_rep(a.n, a.c, a.ratio, C.seed_of(r, a.seed0, a.seed_step), model,
                        js=js, n_eipm=a.n_eipm, with_binning=not a.no_binning)
        sup[r], eipm[r] = rep["sup"], rep["eipm"]
        if not a.no_binning:
            for k, J in enumerate(js):
                bins[k, r] = rep["bins"][J]
                bins_trim[k, r] = rep["bins_trim"][J]
        G, h = rep["G"], rep["h"]
        if (r + 1) % 25 == 0:
            print(f"[worker]   rep {r + 1}/{a.reps}  {time.time() - t0:.1f}s", flush=True)

    meta = {"n": a.n, "c": a.c, "ratio": a.ratio, "reps": a.reps, "kind": a.kind,
            "params": params, "js": list(js), "n_eipm": a.n_eipm, "gh_nodes": a.gh_nodes,
            "seed0": a.seed0, "seed_step": a.seed_step, "sigma_c": model["sigma_c"],
            "elapsed_s": time.time() - t0}
    tmp = a.out + ".tmp.npz"
    np.savez_compressed(tmp, sup_hat=sup, eipm_hat=eipm, bin_hat=bins, bin_trim_hat=bins_trim,
                        js=np.array(js), sup_true=sup_true, eipm_true=eipm_true,
                        n=a.n, c=a.c, ratio=a.ratio, reps=a.reps, G=G, h=h,
                        sigma_c=model["sigma_c"], meta=json.dumps(meta))
    os.replace(tmp, a.out)                       # atomic: a partial file never looks done
    err = sup - sup_true
    print(f"[worker] done in {time.time() - t0:.1f}s  G={G} h={h:.4f}  "
          f"sup bias={err.mean():+.4f} rmse={np.sqrt((err ** 2).mean()):.4f}  -> {a.out}", flush=True)


if __name__ == "__main__":
    main()
